#+TITLE: INF 1501: Culture and Technology I (Fall 2017) - Assignments
#+NAME: Gabby Resch and Matt Ratto
#+STARTUP: showall

# following quote is specific to implosion exercise
"Any interesting being in technoscience, like a textbook, molecule, equation, mouse, pipette, bomb, fungus, technician, agitator, or scientist can - and often should - be teased open to show the sticky economic, technical, political, organic, historical, mythic, and textual threads that make up its tissues." Donna Haraway, Modest_Witness@Second_Millennium, p. 68)

*This course has one connected assignment, split into various parts.* To carry it out, you will need an artifact: some piece of technology that you will study in-depth over the course of the semester. You will grapple with this object in three stages - through two short papers, each worth 25% of the final mark, and a final project worth 35% of the final mark. 

Additionally, participation marks will be earned by preparing informal discussion prompts. These may take the form of provocations, statements, questions, relevant images, etc., and are meant to encourage you to take part in an ongoing dialogue about the themes of the course and the technological artifacts that you and your peers introduce. A minimum of three prompts per student will be expected, with each prompt being worth 5% (up to a total of 15% of the final mark).

This document makes reference to your "group." These are groups of roughly 5 students, chosen randomly at the beginning of each class. While you will be working on individual assignments, group discussion will give you an opportunity to discuss your objects and your developing thoughts about them. 

** Choose an Object
​Due: By end of class, Sept. 18 \\ 
Worth: Unmarked

Choose your object carefully. You are not required to choose a "digital" or "information" technology, but you are strongly encouraged to consider your direction in the MI program. Ask yourself: by studying this artifact, will I explore issues that help me clarify and attain my objectives in the MI? You will want something that relates to your intellectual interests. The more specific your technological artifact, the better. The key to this component of the assignment will be to choose artifacts that will allow you to dig into socio-cultural histories, materialities, and contexts in which you are interested. Over the course of the semester we will collectively work a series of transformations on these objects, culminating in a cumulative individual document. The richness of your analysis will be in part determined by the highly specific connections you can draw between your object and other parts of the world.

** Deconstructing the Object (A)
Length: 8 pages \\
​Due: Oct. 16 \\
Worth: 25%

Each week, you will write approximately one page of text to summarize group discussion around specific thematics and how they relate to your object. These thematics may include topics like the object's material dimensions (e.g. what materials were involved in its production) or its political dimensions (e.g. what kinds of local, national, and international bodies claim jurisdiction over it). What you write is expected to be descriptive and reflexive. It will not be turned in, but a rough draft should be prepared in advance of class so that you "workshop" ideas with your group. This will provide a foundation for your first analytical document, a short paper of approximately 8 pages. In this paper, you will deconstruct your object. You will be tasked with describing; situating it in a context where one might encounter it; and discussing it in relation to thematics that have come up in the course. In order to do this, you might choose to focus on multiple thematics, or select a small number (2 or 3) to read your object through. Something that might guide you in this process will be to think about how your object participates in a larger network of objects. For this assignment, it might be useful to include charts or diagrams that visualize the object's relations.

** Deconstructing the Object (B)
Length: 8 pages \\
​Due: Nov. 13 \\
Worth: 25%

Continue the work started in the previous assignment. Using the reflexive documents that you should have been preparing weekly as a foundation, describe your object in more nuanced detail than in your first assignment. Think of additional vectors to read it through/along, and then bring your object to bear on the more recent thematics that have been discussed in class. Something that might guide you in this assignment will be to think about who the human actors are that build, interact with, control, repair, or destroy your object. For this assignment, it might be useful to include maps, images, gifs, or short videos. 

** Reconstructing the Object
Length: 15 pages \\
Due: Dec. 11 \\
Worth: 35% 

Leading up to the final assignment, you may find it useful to think about where you might have gaps in knowledge with respect to your object. To fill these gaps, think first about the dimensions of the object that you are most familiar with. What interest, passion, or experience has led you to acquire this knowledge? Then, consider what you don't know and how you might go about acquiring new knowledge about your object (recall some of the methods discussed in week 3). Invent something new. 

The final assignment is a bog-standard research paper of the kind that you've likely done dozens of times, except that you have prepared for it with the previous assignments, which should provide a suitable foundation. Up to this point, you have been deconstructing your object - taking it apart; reverse-engineering the black box in which you discovered it; possibly undertaken some kind of media archaeology. For this assignment, you must reconstruct it, but from an entirely speculative perspective. Construct an alternative world in which it might reside. Create a scrapbook from the future. Build an alien user interface for it. Situate it in a game. Ask yourself: what is the one great thing I want to say about this technological artifact I've been thinking about all semester that nobody else has? What tools and styles of writing can I use to communicate this story?

Create visual resources for this final exercise to go alongside the text, but don't neglect the discursive aspect of this exercise. Even if you present a strong material or visual argument, you must also present a textual one. Your goal should be to sketch out a thematic matrix and understand how your speculative object might reside within it. This will require a cogent and well-developed narrative.

This assignment will be marked on argument, creativity, coherence, and style. A 3% per-day late penalty will be applied.
