#+TITLE: INF 1501: Culture and Technology I (Fall 2017) - Syllabus
#+NAME: Gabby Resch and Matt Ratto
#+STARTUP: showall

*Instructors:* Matt Ratto, Faculty of Information, [[mailto:matt.ratto@utoronto.ca][matt.ratto@utoronto.ca]]; Gabby Resch, Faculty of Information, [[mailto:gabby.resch@utoronto.ca][gabby.resch@utoronto.ca]]

*Class times and location:* Monday, BL 507, 6:30-9:30pm

*Office hours:* By appointment

A repository of course materials is located at https://github.com/criticalmaking/INF1501

** Overview
# update and trim
The course is an introduction to various approaches that will help students understand and intervene in the culture-technology nexus. It is intended primarily as an orientation for students in the Culture & Technology concentration of the Masters of Information program, but it endeavours to provide knowledge and skills to any graduate student exploring Science & Technology Studies (STS), Critical Media Studies, or Digital Humanities. In the first part of the course, we explore some of the diverse approaches that have been brought to bear on this rich and densely-populated intersection: philosophical, sociological, anthropological, historical, and literary questions, themes, and methods will be examined. In the second part, we turn to a series of thematics with broad resonance for students interested specifically in information and technology. Throughout the course, our goals will be:
- to challenge normative conceptions of the objects of study (science, technology, culture, information) and consider how the readings help us to come to more nuanced, complex, and effective understandings; 
- to acquire a rough map of the theoretical and methodological approaches that converge on "culture and technology", and understand how different approaches reinforce, complement, and contradict each other; 
- to ask how these analyses can be used as tools to intervene effectively in debates about the appropriate relationship between cultural and technological artifacts in the information age. 

** Class Structure
# getting rid of participation grade? or not???
This course is structured as a /graduate seminar/. We will open each class with a discussion of the course texts and their background; this conversational lecture will rarely last more than an hour. The ensuing discussion will generally last approximately one more hour, and students will be expected to participate actively. Each week, a number of students will be selected to help lead the discussion by identifying themes and questions from the text. This will not be a formal class presentation, but a way for students to practice stepping up and leading a conversation; it will be marked as part of your participation grade.

The final hour or so of class time will be devoted to group work, usually bearing directly on the "Implosion Project" – around which most of your graded work will be based, and about which you will find a great deal more detail in the assignment document. 

At their best, seminars are among the most effective types of classroom environment, but they depend greatly on the engagement and commitment of the students involved. Your active, probing, questioning participation is essential to the class. In past years some students have developed a rich and compelling panoply of tools for understanding these phenomena – while others have sleepwalked their way through class and come out with very little. If you can't bring your best game to class, graduate studies may not be the appropriate option for you. 

** Assignments
# participation or not?
This course has one connected assignment with various parts (see the additional handout), with a balance of 15% based on your participation.
# A quick word about Pass/Fail assignments: if you hand in the pass/fail assignments, your final grade will be the weighted average of your graded assignments.  If, however, you fail to hand in one of more of the Pass/Fail assignments, then the full worth of those assignments (up to 20%) will be /deducted from your grade/.  Therefore: please hand them in.

** Learning Outcomes
# trim a bit
Students in the MI program should familiarize themselves with the [[https://ischool.utoronto.ca/areas-of-study/master-of-information/][MI student learning outcomes]]. As a core course in the /Culture & Technology/ concentration, INF1501 is particularly concerned with helping students become conversant with fundamental concepts, theories, and practices in the social and cultural studies of technology. This includes basic familiarity with core concepts in STS, Media Studies, and cultural Studies. The course assignment is intended to help you cultivate a wide variety of research skills and to begin the process of understanding yourself as an active participant in the intellectual conversations around information technology and its relationship to culture(s). In conjunction with the C&T concentration's other core courses, this class should provide a solid foundation for future professional and intellectual development in the broad spectrum of careers at the intersection of culture and information technology.

** Weekly Readings
You should own the following texts, though copies are also on reserve at the Inforum:  
- Bruno Latour, /We Have Never Been Modern/ 
- Lucy Suchman, /Human-Machine Reconfigurations: Plans and Situated Actions/

# update this list
We will also read parts of a number of books that you may want to own for yourself: Jonathan Sterne's /MP3/; Gillespie, Boczkowski, and Foot's /Media Technologies/; and N. Katherine Hayle's /How We Became Posthuman/. Finally, Sergio Sismondo's /An Introduction to Science and Technology Studies/ offers helpful background on many of the texts and theoretical positions you will encounter in the course. If you find yourself wanting more context, you will find it a thorough and thoughtful field guide.

*** Introduction (Sept. 11)
# see notes
*** What are Culture and Technology? (Sept. 18)
# Theme: Different ways of thinking about culture and technology. Determinism. 
# Discussion Issue: Silicon Valley vs the World
# Questions: What is Culture? What is Technology? What is Nature? What is Society? Who determines these definitions?
# Activity: Settle on an object
# Notes: emphasize that this week carries into the next
- Winner, Langdon. "Technologies as forms of Life", in /The Whale and the Reactor/. 1986.
- Illich, Ivan. /Tools for Conviviality/. New York, Harper & Row. 1973. Ch. 2.
# add one more current piece
# scrap Geertz, Clifford. “Thick Description”, in The Interpretation of Cultures. New York: Basic books, 1973. 3-30.
*** Methods of Interpretation and Analysis (Sept. 25)
# Theme: How have last week's questions been understood by scholars (espcially those in our field)? Introduction to STS methods and themes, incl. SCOT, lab studies, ANT, etc. 
# Discussion Issue: Discursive vs material engagement
# Questions: What are the best ways to parse C&T?
# Activity:
# Notes:
- Pinch, Trevor J., and Wiebe E. Bijker. “The Social Construction of Facts and Artifacts: Or How the Sociology of Technology can Learn from the Sociology of Science.” The Social Construction of Technological Systems: New Directions in the Sociology and History of Technology. 1987. 17-51.
- Latour, We Have Never Been Modern (pp. 1-67, also consider looking at Ch 4 & 5)
- Haraway, Donna. "A Manifesto for Cyborgs", in /The Haraway Reader/. 2004.
# scrap Kuhn, Structure of Scientific Revolutions ch. 3-5, Postscript
# what about adding van der tuin diffractive reading
# Former theme: Paradigms, Structures, Worlds of Difference
*** Epistemologies (Oct. 02)
# Theme: Other ways of knowing. Situated knowledges. Introduction to feminist STS. Gender and knowledge work.
# Discussion Issue: Damore and Google. How tech is built/who builds tech and the epistemic values that are reinforced?
# Questions: What are "feminist" ways of interpreting/making claims about S, C, and T? What are anti-racist and decolonial ways of knowing/making claims? 
# Activity:
# Notes: peterson interview with damore https://www.youtube.com/watch?v=agU-mHFcXdw and another piece on damore https://medium.com/@yonatanzunger/so-about-this-googlers-manifesto-1e3773ed1788
- Donna Haraway, “Situated Knowledges: The Science Question in Feminism and the Privilege of Partial Perspective”.  Feminist Studies 14:3 (1988) 575-599. 
- Eglash, Ron. “Appropriating Technology: An Introduction.” In Appropriating Technology: Vernacular Science and Social Power, by Eglash, Ron, vii–xxi, 2004. http://homepages.rpi.edu/~eglash/eglash.dir/at/intro.pdf 
# maybe add harding rethinking standpoint epistemology and scrap eglash
# maybe add in teddy bear patriarchy
# scrap Maureen McNeil, “Feminist Cultural Studies of Science and Technology: Roots and Routes” in Feminist Cultural Studies of Science and Technology. New York: Routledge, 2007.  11-24
# Former theme: Beyond "Society"
*** THANKSGIVING - NO CLASS (Oct. 09)
*** Truth and Authority (Oct. 16)
# Theme: Authority to make claims about the world. Primer on "truth" as a structuring concept for how we think about C&T. Sokal affair and its continuing legacy. Recent Sokal 2.0. Continuation of discussion from epistemologies week.
# Discussion Issue:
# Questions:
# Activity: Detecting fake news with ML ipynb walkthrough https://www.datacamp.com/community/tutorials/scikit-learn-fake-news#gs.iCKzzh0
# Notes: take a look at biella coleman's mcgill course on scientific controversy: https://groups.google.com/forum/#!msg/stsgrad/G1-jryk91W4/PnbzOe6ZBwAJ. also take a look at calling bullshit course at UW. 
- readings from how to lie with statistics; truth, damn truth, and statistics; graphesis
# Former theme: open week
*** Materialism(s) (Oct. 23)
# Theme: Material|digital entanglement
# Discussion Issue:
# Questions:
# Activity:
# Notes: interview with barad about new materialism in umichigan thing: https://quod.lib.umich.edu/o/ohp/11515701.0001.001/1:4.3/--new-materialism-interviews-cartographies?rgn=div2;view=fulltext
- Laet, Marianne de, and Annemarie Mol. 2000. “The Zimbabwe Bush Pump: Mechanics of a Fluid Technology.” Social Studies of Science 30 (2): 225–63. doi:10.2307/285835.
- Sterne, "What do we want? Materiality. When do we want it? Now!"  in Boczkowski, Pablo J., Kirsten A. Foot, and Tarleton Gillespie, eds. Media Technologies : Essays on Communication, Materiality, and Society. Cambridge, MA: The MIT Press, 2014. 119-128.
# maybe scrap sterne and add something else...
*** Information and the Body (Oct. 30)
# Theme: The "Informational" body. Biological determinism and technology.
# Discussion Issue: 2045 disembodied consciousness. 
# Questions:
# Activity:
# Notes:
- N. Katherine Hayles, How We Became Posthuman ch 1,4. 
- Wiener, "Human Use of Human Beings", Ch 1-2 of second edition.
# there's better stuff than wiener himself. we could just do something that introduces him. i think chapters 7 and 8 in gleick's book might work. 
# Maybe Ihde. Postphenomenology, Embodiment and Transhumanism
*** READING WEEK – NO CLASS (NOV. 06)
*** Interactions (Nov. 13)
# Theme: Interaction(s) between humans and technology
# Discussion Issue: The "user"
# Questions: 
# Activity:
# Notes:
- Suchman, Human-Machine Reconfigurations  (Ch 1-5, 11, 15)
# too much suchman. should add something. Olia Lialina Turing Complete User.
# if adding ihde to previous week, need to emphasize the crossover to this week. see rosenberger and verbeek's book
*** Infrastructures (Nov. 20)
# Theme: The black box of infrastructure. Not that we can't "know" the cloud, but that the people who support it are erased. Politics of infrastructures. National technologies and the sublime. Manifest destiny. Nationhood and the technological.
# Discussion Issue: Where is the internet?
# Questions: Who builds technology? Who is expected to use technology? Who is expected to maintain it? Who controls infrastructure?
# Activity: Infrastructure tourism
# Notes:
- Harvey, Penny, and Hannah Knox. “The Enchantments of Infrastructure.” Mobilities 7, no. 4 (2012): 521–36. doi:10.1080/17450101.2012.718935. 
- Bowker et al., “Toward Information Infrastructures”, in . Hunsinger et al. (eds.),International Handbook of Internet Research. Springer: 2010.
# no leigh star? what about ethnography of infrastructure
*** Standards (Nov. 27)
# consider flipping the order of this week and the last week
# Theme: Standards. Formats. Interoperability. Relationship between infrastructures and standards. 
# Discussion Issue: 
# Questions: 
# Activity:
# Notes:
- Jonathan Sterne, “Nature Builds No Telephones” in  MP3 : The Meaning of a Format. Durham: Duke University Press, 2012.
- Jonathan Sterne. “The mp3 as Cultural Artifact.” New Media and Society 8, no. 5 (2006): 825–42.
# scrap one sterne article and replace with something. maybe introduce boundary objects.
# scrap Adrian MacKenzie, "Codecs" in Software Studies: A Lexicon 
# former theme: codecs
*** Algorithmic Life (Dec. 04)
# Theme: Data-driven everything. Surveillance. Algorithmic labour. 
# Discussion Issue: Uber. Amazon. Gig economy. Peer-to-peer society.
# Questions:
# Activity:
# Notes: reiterate the connection between this and the week on information and the body
- Gillespie, “The Relevance of Algorithms” in Boczkowski, Pablo J., Kirsten A. Foot, and Tarleton. Gillespie, eds. Media Technologies: Essays on Communication, Materiality, and Society. Cambridge, MA: The MIT Press, 2014.
- Amoore, Louise. “Algorithmic War: Everyday Geographies of the War on Terror.” Antipode 41, no. 1 (January 2009): 49–69. doi:10.1111/j.1467-8330.2008.00655.x.
# add something about automation
# bogost cathedral of computation
# morozov tamin of tech criticism https://thebaffler.com/salvos/taming-tech-criticism
# scrap Sharkey & Suchman. “Wishful Mnemonics and Autonomous Killing Machines.” Proceedings of the AISB 136 (May 2013): 14–22.
*** Connectivity - FINAL CLASS (Dec. 11)
# Theme: Entertainment media. Pervasive screens. The attention economy. Social media society. Echo chambers. Alienation.
# Discussion Issue: Have cellphones destroyed a generation?
# Questions:
# Activity:
# Notes: need to prompt them at the end for what they'll work toward in culture and tech II as far as intervening. morozov on connectivity http://www.newyorker.com/magazine/2013/10/28/only-disconnect-2
- postman - amusing ourselves to death. 
# scrap Grimes, Sara M., and Andrew Feenberg. 2009. “Rationalizing Play: A Critical Theory of Digital Gaming.” The Information Society 25 (2): 105–18.
# former theme: games
